name: android_sms_consent
description: Flutter plugin to perform one-tap SMS verification with the SMS User Consent API in Android.
version: 1.0.1
homepage: https://khalti.com
issue_tracker: https://github.com/khalti/android_sms_consent/issues
repository: https://github.com/khalti/android_sms_consent

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.khalti.android_sms_consent
        pluginClass: AndroidSmsConsentPlugin
